Improving the dependencies installation, checking platform, and couple bugs

diff --git a/run-command/network-loss-stress.yml b/run-command/network-loss-stress.yml
--- a/run-command/network-loss-stress.yml
+++ b/run-command/network-loss-stress.yml
@@ -1,63 +1,144 @@
 ---
-description: Adding packet loss to the network (default eth0)
+description: |
+  ## What does this document do?
+  Adding packet loss to the network
+  Drops 7% of packets with 25% correlation
+  7% is enough that TCP should not fail completely
+
+  ## Input Parameters
+  * Interface: The interface to add delay to (default: eth0).
+  * Loss: The percent of packet to drop (default: 7).
+  * Correlation: The correlation - in percent - with previous packet loss (default: 25).
+  * Duration: The duration - in seconds - of the test (default: 60).
+  * InstallDependencies: If set to True, Systems Manager installs the required dependencies on the target instances. (default: True).
+
+  ## Output Parameters
+  None.
+
 schemaVersion: '2.2'
 parameters:
-  interface:
+  Interface:
     type: String
-    description: Specify the interface to add loss to. (Required)
-    default: eth0
-  loss:
+    description: "The interface to add delay to (default: eth0)."
+    default: "eth0"
+    allowedPattern: '^[0-9a-zA-Z\-]{1,15}$'
+  Loss:
     type: String
-    description: The % of packet to drop.
+    description: "The percent of packet to drop. (default: 7)."
     default: "7"
-  correlation:
+    allowedPattern: "^[0-9]+$"
+  Correlation:
     type: String
-    description: The correlation with previous packet loss.
+    description: "The correlation with previous packet (default: 25)."
     default: "25"
-  # Drops 7% of packets with 25% correlation
-  # 7% is enough that TCP will not fail completely
-  duration:
+    allowedPattern: "^[0-9]+$"
+  Duration:
     type: String
-    description: The duration - in minutes - of the attack. (Required)
-    default: "1"
+    description: "The duration - in seconds - of the test (default: 60)."
+    default: "60"
+    allowedPattern: "^[0-9]+$"
   InstallDependencies:
     type: String
-    description: 'If set to True, Systems Manager installs the required dependencies on the target instances (Required)'
+    description: "If set to True, Systems Manager installs the required dependencies on the target instances. (default: True)."
     default: 'True'
     allowedValues:
-    - 'True'
-    - 'False'
+      - 'True'
+      - 'False'
 mainSteps:
-- action: aws:runShellScript
-  name: InstallDependencies
-  inputs:
-    runCommand:
-    - "#!/bin/bash"
-    - if  [[ "{{InstallDependencies}}" == True ]] ; then
-    - '   echo "Installing required dependencies" >&2'
-    - '   if [ -f  "/etc/system-release" ] ; then'
-    - "     if cat /etc/system-release|grep -i 'Amazon Linux' ; then "
-    - "       sudo yum -y install tc "
-    - "     else"
-    - '       echo "There was a problem installing dependencies." >&2'
-    - "       exit 1"
-    - "     fi"
-    - "   elif cat /etc/issue|grep -i Ubuntu ; then "
-    - "     sudo apt-get update -y"
-    - "     sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tc"
-    - "   else"
-    - '     echo "There was a problem installing dependencies." >&2'
-    - "     exit 1"
-    - "   fi"
-    - fi
-- action: aws:runShellScript
-  name: RevertCommandScheduling
-  inputs:
-    runCommand:
-    - "echo 'tc qdisc del dev {{ interface }} root netem loss {{ loss }}% {{ correlation }}%' | at now + {{ duration }} minutes"
-- action: aws:runShellScript
-  name: AlterNetworkInterface
-  inputs:
-    runCommand:
-    - "tc qdisc add dev {{ interface }} root netem loss {{ loss }}% {{ correlation }}%"
-    - "tc qdisc show"
+  - action: aws:runShellScript
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    name: InstallDependencies
+    description: |
+      ## Parameter: InstallDependencies
+      If set to True, this step installs the required dependecy via operating system's repository. It supports both
+      Debian (apt) and CentOS (yum) based package managers.
+    inputs:
+      runCommand:
+        - |
+          #!/bin/bash
+          if  [[ "{{ InstallDependencies }}" == True ]] ; then
+            if [[ "$( which tc 2>/dev/null )" ]] ; then echo Dependency is already installed. ; exit ; fi
+            echo "Installing required dependencies"
+            if [ -f  "/etc/system-release" ] ; then
+              if cat /etc/system-release | grep -i 'Amazon Linux' ; then
+                sudo amazon-linux-extras install testing
+                sudo yum -y install tc
+              else
+                echo "There was a problem installing dependencies."
+                exit 1
+              fi
+            elif cat /etc/issue | grep -i Ubuntu ; then
+              sudo apt-get update -y
+              sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y iproute2
+            else
+              echo "There was a problem installing dependencies."
+              exit 1
+            fi
+          fi
+  - action: aws:runShellScript
+    precondition:
+      StringEquals:
+        - platformType
+        - Linux
+    name: AlterNetworkInterface
+    description: |
+      ## Parameters: Interface, Loss, Correlation and Duration
+      This step adds a `Loss` (in percent) to `Interface` for the given `Duration` (in seconds), using the `tc` (Traffic Control) command.
+      The script will inject packet drop on the network, and wait for the given duration to remove that. It has two rollback mechanisms in place:
+      * It will listen for exit signals (SIGINT and SIGTERM), and will stop the packet drop injection if any of them is received.
+      * It will periodically enqueue rollback checks into a queue (using `at` command). This way, if the command is stopped and the rollback
+      was not executed, the enqueued commands will try to stop it. (for example, if the command is stopped using kill -9). This is just
+      and extra safety check to avoid the fault to remain injected after the script is no longer running.
+    inputs:
+      maxAttempts: 1
+      runCommand:
+        - |
+          MAX_FLAG_AGE_SECONDS=5
+          ATTEMPT_ROLLBACK_AT_SECONDS=10
+          STOP_TIME=$(( $(date +%s) + {{ Duration }} ))
+
+          RANDOM_STRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)
+          FLAG_PATH="/tmp/AWSFIS-Run-Network-Packet-Drop-$RANDOM_STRING.flag"
+          ROLLBACK_COMMAND="tc qdisc del dev {{ Interface }} root netem loss {{ Loss }}% {{ Correlation }}%"
+          ROLLBACK_CHECK='if [[ ( ! -f "'$FLAG_PATH'" ) || "$(( $(date +%s) - $(stat -c "%Y" '$FLAG_PATH') ))" -gt '$MAX_FLAG_AGE_SECONDS' ]]; then rm '$FLAG_PATH'; '$ROLLBACK_COMMAND' ; fi 2>/dev/null'
+
+          # this will enqueue a rollback check, after $ATTEMPT_ROLLBACK_AT_SECONDS seconds
+          function schedule_rollback_attempt {
+            echo "sleep $ATTEMPT_ROLLBACK_AT_SECONDS; $ROLLBACK_CHECK" | at now
+          }
+
+          # this will delete the flag file, and rollback the fault injection
+          function rollback {
+            rm $FLAG_PATH
+            $ROLLBACK_COMMAND
+            exit $?
+          }
+
+          # this will inject some packet drop on the network
+          function inject_packet_drop {
+            echo "Injecting packet drop..."
+            tc qdisc add dev {{ Interface }} root netem loss {{ Loss }}% {{ Correlation }}%
+          }
+
+          # binding the rollback function to these exit signals
+          trap rollback SIGINT
+          trap rollback SIGTERM
+
+          # atd must be running in order to use at later
+          atd
+
+          schedule_rollback_attempt
+          inject_packet_drop
+
+          # for the duration of the injection, the flag file is updated, and a rollback check is enqueued
+          while [[ $(date +%s) -lt $STOP_TIME ]] ; do
+            touch $FLAG_PATH
+            schedule_rollback_attempt
+            sleep $MAX_FLAG_AGE_SECONDS
+          done
+
+          # after the desired duration, the injection is removed
+          rollback
